# Generated by Django 4.0.6 on 2022-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_name_alter_department_member_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_member',
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('member', 'name'), name='unique_member'),
        ),
    ]
