# Generated by Django 4.0.6 on 2022-07-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_department_unique_member'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='unique_member',
        ),
    ]
