name: Build Docker Container & Push to DO Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: kenfelix/TlemiBringUpProd/.github/workflows/test.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: tlemi-bring-up-k8s
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Insall doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to DO Container Registry with short-lived creds
        run: doctl registry login --expiry-seconds 1200
      - name: Build container image
        working-directory: ./backend
        run: |
          docker build -f Dockerfile \
            -t registry.digitalocean.com/takjug/tlemi-bringup-k8s-api:latest \
            -t registry.digitalocean.com/takjug/tlemi-bringup-k8s-api:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} \
            .
      - name: Push image
        run: |
          docker push registry.digitalocean.com/takjug/tlemi-bringup-k8s-api --all-tags
      - name: K8s cluster kubeconfig file with/ short-lived creds
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Update deployment secrets
        run: |
          cat << EOF >> backend/.env.prod
          DJANGO_SUPER_USERNAME=${{ secrets.DJANGO_SUPER_USERNAME }}
          DJANGO_SUPER_PASSWORD=${{ secrets.DJANGO_SUPER_PASSWORD }}
          DJANGO_SUPER_EMAIL=${{ secrets.DJANGO_SUERP_EMAIL }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          ENV_ALLOWED_HOST=${{ secrets.ENV_ALLOWED_HOST }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          APPLICATION_ID=${{ secrets.APPLICATION_ID }}
          API_KEY=${{ secrets.API_KEY }}
          INDEX_PREFIX=${{ secrets.INDEX_PREFIX }}
          TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_DEFAULT_CALLERID=${{ secrets.TWILIO_DEFAULT_CALLERID }}
          EOF
          kubectl delete secret tlemi-bringup-k8s-api-env
          kubectl create secret generic tlemi-bringup-k8s-api-env --from-env-file=backend/.env.prod
      - name: Update Deployment image
        run: |
          kubectl set image deployment/tlemi-bringup-k8s-api-deployment tlemi-bringup-k8s-api=registry.digitalocean.com/takjug/tlemi-bringup-k8s-api:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Wait for rollout to finish
        run: |
          kubectl rollout status deployment/tlemi-bringup-k8s-api-deployment
      - name: Post-build Django Commands - Migrate / Collectstatic
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=tlemi-bringup-k8s-api-deployment -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- bash /app/migrate.sh